@extends('layouts.app')
@section('title', 'Admin promo codes')
@section('content')
<div class="page-head"><div><span class="eyebrow">ADMINISTRATION</span><h1>Promo codes</h1></div><a class="button secondary" href="{{ route('admin.dashboard') }}">Back to admin</a></div>
<section class="panel"><h2>Create promo code</h2><form method="post" action="{{ route('admin.promos.store') }}" class="stack">@csrf
<div class="filter-grid"><label>Code<input name="code" placeholder="WELCOME500" required></label><label>Title<input name="title" required></label><label>Credits<input name="credits" type="number" min="1" max="100000" required></label><label>Max redemptions<input name="max_redemptions" type="number" min="1" placeholder="Unlimited"></label></div>
<label>Description<textarea name="description" rows="2"></textarea></label><div class="filter-grid"><label>Starts at<input name="starts_at" type="datetime-local"></label><label>Ends at<input name="ends_at" type="datetime-local"></label><label class="check"><input name="active" type="checkbox" value="1" checked> Active</label></div><button class="button" type="submit">Create code</button></form></section>
<section class="panel"><h2>Existing codes</h2><div class="admin-card-list">
@forelse($promos as $promo)<article class="admin-item"><div class="section-head"><div><code>{{ $promo->code }}</code><h3>{{ $promo->title }}</h3></div><span class="status-pill {{ $promo->active ? '' : 'status-muted' }}">{{ $promo->active ? 'Active' : 'Inactive' }}</span></div>
<p>{{ $promo->description ?: 'No description.' }}</p><div class="mini-stats"><span><strong>{{ number_format($promo->credits) }}</strong> credits</span><span><strong>{{ number_format($promo->redemptions_count) }}</strong> / {{ $promo->max_redemptions ? number_format($promo->max_redemptions) : '∞' }}</span><span>{{ $promo->ends_at?->format('Y-m-d H:i') ?: 'No expiry' }}</span></div>
<form method="post" action="{{ route('admin.promos.update', $promo) }}" class="stack compact">@csrf @method('PUT')<div class="filter-grid"><label>Code<input name="code" value="{{ $promo->code }}" required></label><label>Title<input name="title" value="{{ $promo->title }}" required></label><label>Credits<input name="credits" type="number" value="{{ $promo->credits }}" min="1" required></label><label>Max uses<input name="max_redemptions" type="number" value="{{ $promo->max_redemptions }}" min="1"></label></div><label>Description<textarea name="description" rows="2">{{ $promo->description }}</textarea></label><div class="filter-grid"><label>Starts<input name="starts_at" type="datetime-local" value="{{ $promo->starts_at?->format('Y-m-d\\TH:i') }}"></label><label>Ends<input name="ends_at" type="datetime-local" value="{{ $promo->ends_at?->format('Y-m-d\\TH:i') }}"></label><label class="check"><input name="active" type="checkbox" value="1" @checked($promo->active)> Active</label></div><button class="button secondary" type="submit">Save changes</button></form>
<form method="post" action="{{ route('admin.promos.toggle', $promo) }}" class="inline-form">@csrf<button class="link-button" type="submit">{{ $promo->active ? 'Deactivate' : 'Activate' }}</button></form></article>@empty<p>No promo codes yet.</p>@endforelse
</div></section>
@endsection
