@extends('layouts.app')
@section('title', 'Live operations')
@section('content')
<div class="page-head"><div><span class="eyebrow">REAL-TIME OPERATIONS</span><h1>Live activity</h1><p class="hint">Presence, support activity and the transient event stream refresh automatically.</p></div><div class="live-status"><span class="live-dot"></span><strong>Live</strong><small data-live-generated>Connecting…</small></div></div>
<div class="grid stats"><div class="stat"><span>Online now</span><strong data-live-online-count>{{ number_format($onlineUsers->count()) }}</strong></div><div class="stat"><span>Open tickets</span><strong data-live-open-tickets>{{ number_format($openTickets) }}</strong></div><div class="stat"><span>Pending tickets</span><strong data-live-pending-tickets>{{ number_format($pendingTickets) }}</strong></div><div class="stat"><span>Recent events</span><strong data-live-event-count>{{ number_format($recentEvents->count()) }}</strong></div><div class="stat"><span>Refresh</span><strong>{{ number_format(config('live.poll_ms', 4000) / 1000, 1) }}s</strong></div></div>
<section class="grid two" data-admin-live-url="{{ route('admin.live.data') }}">
<div class="panel"><div class="section-head"><h2>Online users</h2><span class="status-pill ok">Last {{ config('live.presence_window_minutes', 5) }} min</span></div><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Current path</th><th>Last seen</th></tr></thead><tbody data-live-online-body>@forelse($onlineUsers as $presence)<tr><td><strong>{{ $presence->user?->name ?? 'Unknown' }}</strong><br><small>{{ $presence->user?->email }}</small></td><td>{{ $presence->user?->is_admin ? str_replace('_', ' ', $presence->user?->resolvedAdminRole() ?? 'admin') : 'player' }}</td><td><code>{{ $presence->current_path }}</code></td><td>{{ $presence->last_seen_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="4">No recently active users.</td></tr>@endforelse</tbody></table></div></div>
<div class="panel"><div class="section-head"><h2>Transient event stream</h2><span class="status-pill warning">Ephemeral</span></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Audience</th><th>Topic</th><th>Event</th><th>Created</th></tr></thead><tbody data-live-events-body>@forelse($recentEvents as $event)<tr><td>#{{ $event->id }}</td><td>{{ $event->audience }}</td><td>{{ $event->topic }}</td><td><code>{{ $event->event_type }}</code></td><td>{{ $event->created_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="5">No live events yet.</td></tr>@endforelse</tbody></table></div></div>
</section>
@endsection
